export const HEADLINES = [
  'Mama minta pulsa',
  'Kearifan lokal yang dibungkam',
  'Banjir di Cikini',
  'A.C.A.B',
  'Bukan kupu-kupu malam',
  'Buang sampah masih sembarangan',
  'Cokil master',
  'Monas ditebang',
  'Kebakaran hutan di kalimantan',
  'Melindungi dan melayani siapa',
  'Haji Jepri ulang tahun',
  'Udah ambil laundry belom?',
  'Konglomerat Sawit dapat suntikan dana',
  'Tanjung Priok demo',
  'Berilah hambamu uang',
  'Keraton Agung Sejagat bubar',
  'Ekstase dalam agoni, nikmati simfoni bunuh diri',
  'Kau ciptakan surga bernama plaza',
  'Dimensi Alam keterasingan',
  'Acara ini acara lo juga nyet',
  'Kalo gak lo siapa lagi?',
  'Enak jaman purba, lebih berbagi',
  'Jangan makan baterai',
  'Subsidi mega 7,5 triliun',
  'Aplikasi karya anak bangsa',
  'Ngerampok di warteg, emang gak ada CCTV?'
];
